import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google"; 
import "./globals.css";
import Navbar from './components/Navbar';
import { ClerkProvider } from '@clerk/nextjs';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "600"], // You can choose more or fewer weights
  subsets: ["latin"],
  variable: "--font-poppins", // ✅ Add a CSS variable name
});

export const metadata: Metadata = {
  title: "AI RAG Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
        >
          <nav>
            <Navbar />
          </nav>
          {children}
        </body>
      </html>
     </ClerkProvider>
  );
}
